WITH
	E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10),
	D	AS (SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME , E10.DEPTNO , D.DNAME , D.LOC 
FROM E10,D 
WHERE E10.DEPTNO = D.DEPTNO;

SELECT * FROM EMP WHERE DEPTNO = 10;

SELECT * FROM DEPT;

--1
SELECT SUBSTR(ENAME,1,2) AS EN , ENAME FROM EMP;
SELECT LPAD(ENAME,2) AS EN , ENAME FROM EMP;
SELECT REPLACE(ENAME,SUBSTR(ENAME,3) , '') AS EN , ENAME FROM EMP;

--2 

SELECT SUBSTR(ENAME,0,2) || '****' AS EN , ENAME FROM EMP;
SELECT LPAD(ENAME,2) || '****' AS EN , ENAME FROM EMP;
SELECT REPLACE(ENAME,SUBSTR(ENAME,3) , '') || '****' AS EN , ENAME FROM EMP;

--3 

SELECT RPAD(LPAD(ENAME,2), LENGTH(ENAME) , '*') AS EN , ENAME FROM EMP;
SELECT RPAD(SUBSTR(ENAME,0,2), LENGTH(ENAME), '*')  AS EN , ENAME FROM EMP;
SELECT REPLACE(ENAME,SUBSTR(ENAME,3) , '') || RPAD('*', LENGTH(ENAME) - 2, '*') AS EN , ENAME FROM EMP;

SELECT 
	ceil(3.14),
	floor(3.14),
	ceil(-3.14),
	floor(-3.14),
	trunc(-3.14)
FROM dual;


SELECT to_char(sysdate, 'yyyy"년"') FROM dual;
SELECT to_char('0000') AS aa FROM dual;

--1 
SELECT EMPNO , 
	RPAD(SUBSTR(EMPNO , 1 , 2 ), LENGTH(EMPNO) , '*')  AS MASKING_EMPNO, 
	ENAME , 
	RPAD(SUBSTR(ENAME  , 1 , 1 ), LENGTH(ENAME) , '*') AS MASKING_ENAME 
FROM EMP
WHERE 
	LENGTH(ENAME) >= 5 AND LENGTH(ENAME) < 6
;
--2 
SELECT EMPNO , ENAME , SAL , TRUNC(SAL / 21.5 , 2) AS DAY_PAY , ROUND( (SAL / 21.5) / 8 , 1) AS TIME_PAY
FROM EMP e ;

--3
SELECT 
	EMPNO , 
	ENAME , 
	HIREDATE, 
	TO_CHAR(ADD_MONTHS(HIREDATE , 3 ), 'YYYY-MM-DD') AS R_JOB, 
	NVL2(COMM , TO_CHAR(COMM) , 'N/A') AS COMM
FROM EMP;
--4
SELECT empno , ename , mgr , 
CASE 
	WHEN mgr IS NULL THEN '0000' 
	WHEN SUBSTR(MGR , 1, 2 ) = '75' THEN '5555'
END as chg_mgr 
FROM EMP 
